name : CI Pipeline
on : push
jobs :
  runs-on: ubuntu-latest
  steps :
  
    - name : Checkout Code
      uses : action@Checkout@4

    - name : Setup Python 
      uses : actions/setup-python@v4
      with :
        python-version: '3.10'